[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss04"

    [buildPlans.IosevkaCustom.variants.design]
    capital-m = "flat-bottom-serifless"
    capital-q = "curly-tailed"
    capital-w = "straight-flat-top-serifless"
    f = "flat-hook-serifed-crossbar-at-x-height"
    r = "serifed"
    w = "straight-flat-top-serifless"
    long-s = "flat-hook-double-serifed-xh"
    eszet = "longs-s-lig-middle-serifed-xh"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ka = "symmetric-connected-serifless"
    cyrl-ka = "symmetric-connected-serifless"
    cyrl-em = "flat-bottom-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    ampersand = "closed"
    at = "fourfold"
    bar = "natural-slope"

    [buildPlans.IosevkaCustom.variants.italic]
    capital-m = "flat-bottom-serifless"
    capital-q = "curly-tailed"
    capital-w = "straight-flat-top-serifless"
    e = "rounded"
    f = "flat-hook-extended-crossbar-at-x-height"
    r = "serifed"
    w = "straight-flat-top-serifless"
    long-s = "flat-hook-descending-middle-serifed-xh"
    eszet = "longs-s-lig-descending-middle-serifed-xh"
    cyrl-capital-zhe = "symmetric-connected"
    cyrl-zhe = "symmetric-connected"
    cyrl-capital-ka = "symmetric-connected-serifless"
    cyrl-ka = "symmetric-connected-serifless"
    cyrl-em = "flat-bottom-serifless"
    tittle = "round"
    diacritic-dot = "round"
    punctuation-dot = "round"
    braille-dot = "round"
    at = "fourfold"
    bar = "natural-slope"

[buildPlans.IosevkaCustom.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
